# Generated by Django 4.2.1 on 2023-08-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('matricula_API', models.BigIntegerField(blank=True, null=True)),
                ('senha_API', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_curso', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagem', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetosIntegradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('periodo_inicial', models.DateField()),
                ('periodo_final', models.DateField()),
                ('resumo', models.CharField(max_length=250)),
                ('resultados', models.CharField(max_length=150)),
                ('Curso_idCurso', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exemplo.cursos')),
            ],
        ),
    ]
