# Generated by Django 4.2.1 on 2023-05-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetosintegradores',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
