# Generated by Django 4.2.1 on 2023-07-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0002_alter_projetosintegradores_imagem'),
        ('exemplo', '0002_imagem_delete_ano_remove_projetosintegradores_imagem'),
    ]

    operations = [
    ]
