# Generated by Django 4.2.1 on 2023-07-11 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0003_merge_20230711_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetosintegradores',
            name='Ano_idAno',
        ),
        migrations.RemoveField(
            model_name='projetosintegradores',
            name='imagem',
        ),
        migrations.AddField(
            model_name='imagem',
            name='ProjetosIntegradores_idProjetoIntegradores',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exemplo.projetosintegradores'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='Imagem',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='projetosintegradores',
            name='Curso_idCurso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exemplo.cursos'),
        ),
    ]
