# Generated by Django 4.2.1 on 2023-07-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0004_remove_projetosintegradores_ano_idano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='ProjetosIntegradores_idProjetoIntegradores',
        ),
    ]
